# Generated by Django 2.1.3 on 2018-11-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20181126_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='event_start',
        ),
    ]
