# Generated by Django 2.1.3 on 2018-11-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20181126_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_start',
            new_name='start',
        ),
    ]
