# Generated by Django 2.1.3 on 2018-11-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20181126_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='End'),
        ),
    ]
